# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "infra-state-wordpress-site-reflection2111"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "eu-north-1"
    use_lockfile = true
  }
}
