---
# handlers file for jenkins-master
- name: update_cache_docker
  apt:
    update_cache: yes
  become: true
  tags: install_docker

- name: restart_docker
  service:
    name: docker
    state: reloaded
  become: true
  tags: install_docker
